### ISSUE TITLE
workflow-status: publish human readable value

### ISSUE THREAD

**Issue by dprelipcean** [reanahub/reana-commons#138] opened 2019-09-09 13:48 UTC
The workflow engines should publish human-readable statuses taken from [reana-db](https://github.com/reanahub/reana-db/blob/master/reana_db/models.py#L56), e.g. for the [cwl engine](https://github.com/reanahub/reana-workflow-engine-cwl/blob/30e7ee448827138655b4215b020ef3257b731fa9/reana_workflow_engine_cwl/tasks.py#L63): publishing should change from:
```console
publisher.publish_workflow_status(workflow_uuid, 2)
```
to
```console
publisher.publish_workflow_status(workflow_uuid, WorkflowStatus.finished)
```

**Comment by diegodelemos** [comment] 2019-10-04 14:02
Closing as duplicate of https://github.com/reanahub/reana-workflow-controller/issues/204.

**Closed by diegodelemos** 2019-10-04 14:02 UTC
Labels: system/refactor
